In [2]:
#LightNVM 

import numpy as np 

def changeFormatOfDataForSVMLight(a_list, spm) :

    for idx1, var1 in enumerate(a_list) :
        temp_str = str()
        temp = var1.split()
        for idx2, var2 in enumerate(temp) :
            temp_var = float(var2)
            if spm == True : 
                if idx2 == 0 :
                    temp_str += ("-1\t"+str(idx2+1)+":"+str(temp_var)+"\t")
                elif idx2 == (len(a_list)-1) :
                    temp_str += (str(idx2+1)+":"+str(temp_var))
                else :
                    temp_str += (str(idx2+1)+":"+str(temp_var)+"\t")
            else :
                if idx2 == 0 :
                    temp_str += ("+1\t"+str(idx2+1)+":"+str(temp_var)+"\t")
                elif idx2 == (len(a_list)-1) :
                    temp_str += (str(idx2+1)+":"+str(temp_var))
                else :
                    temp_str += (str(idx2+1)+":"+str(temp_var)+"\t")
        a_list[idx1] = temp_str
    return a_list
    

def WriteArrayForSVM_light(file_handler, a_list) :
    for idx, var in enumerate(a_list) :
            if idx <= 10 :
                print (idx)
            file_handler.write(var+"\n")
            
# @ function : Read a file without blank line
# For example : 
# ["Hellow world\n", "\n", "Hi\n"] --> ["Hellow world\n", "Hi\n"]
# input : file path 
# output : a set of Lists of Words
def readAFileLineByLine (file_path) :
    f = open(file_path, "r")
    # due to iconv not dealing with conversion between EUC-KR and UTF-8
    a_whole_list = [x for x in f.readlines() if x != "\n"]
    f.close()
    # For Debugging
    print ("Currently, The file(" + file_path, ") read")    
    return a_whole_list


CBOW_testSen2Vec = ["/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/CBOW_HAMVector",
             "/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/CBOW_SPMVector"]
CBOW_trainSen2Vec = ["/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/CBOW_HAMvector",
              "/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/CBOW_SPMVector"]

SKIP_GRAM_testSen2Vec =["/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/SKIP_GRAM_HAMVector",
             "/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/SKIP_GRAM_SPMVector"]
SKIP_GRAM_trainSen2Vec = ["/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/SKIP_GRAM_HAMvector",
              "/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/SKIP_GRAM_SPMVector"]


# To store it in the 
CBOW_SVM_Lihgt_test = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/test/CBOW_SVM_Light_test"

CBOW_SVM_Lihgt_train = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/train/CBOW_SVM_Light_train"
                              
SKIP_GRAM_SVM_Lihgt_test = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/test/SKIP_GRAM_SVM_Light_test"

SKIP_GRAM_SVM_Lihgt_train = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/train/SKIP_GRAM_SVM_Light_train"
                     

def main(test_ham, test_spm, train_ham, train_spm, target_train, target_test) :
    path1 = test_ham
    path2 = test_spm
    path3 = train_ham
    path4 = train_spm
    
    #for SVM Light 
    svm_light_train=target_train
    svm_light_test=target_test
   
    # for Test
    test_ham_list=readAFileLineByLine(path1)
    test_ham_svm = changeFormatOfDataForSVMLight(test_ham_list, False)
    
    print ("len of test_ham_svm:", len(test_ham_svm))
    
    test_spm_list=readAFileLineByLine(path2)
    test_spm_svm = changeFormatOfDataForSVMLight(test_spm_list, True)
    
    print ("len of test_spm_svm:", len(test_spm_svm))
    
    test_svm = test_ham_svm + test_spm_svm 
    print ("len of test_svm:", len(test_svm))
    print (test_svm[-1])
    with open(svm_light_test, "w") as svm_light_test_writer : 
            WriteArrayForSVM_light(svm_light_test_writer, test_svm)
    
    # for train
    train_ham_list=readAFileLineByLine(path3)
    train_ham_svm = changeFormatOfDataForSVMLight(train_ham_list, False)
    
    print ("len of train_ham_svm:", len(train_ham_svm))
    
    train_spm_list=readAFileLineByLine(path4)
    train_spm_svm = changeFormatOfDataForSVMLight(train_spm_list, True)
    
    print ("len of train_spm_svm:", len(train_spm_svm))  

    train_svm = train_ham_svm + train_spm_svm
    print ("len of train_svm:", len(train_svm)) 
    print (train_svm[-1])
    with open(svm_light_train, "w") as svm_light_train_writer : 
            WriteArrayForSVM_light(svm_light_train_writer, train_svm)
    
    print (len(test_svm))
    print (len(train_svm))
    
    
if __name__ == "__main__" :
    #main(CBOW_testSen2Vec[0], CBOW_testSen2Vec[1], CBOW_trainSen2Vec[0], CBOW_trainSen2Vec[1], CBOW_SVM_Lihgt_train, CBOW_SVM_Lihgt_test)
    main(SKIP_GRAM_testSen2Vec[0], SKIP_GRAM_testSen2Vec[1], SKIP_GRAM_trainSen2Vec[0], SKIP_GRAM_trainSen2Vec[1], SKIP_GRAM_SVM_Lihgt_train, SKIP_GRAM_SVM_Lihgt_test)

Currently, The file(/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/SKIP_GRAM_HAMVector ) read
len of test_ham_svm: 5000
Currently, The file(/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/SKIP_GRAM_SPMVector ) read
len of test_spm_svm: 5000
len of test_svm: 10000
-1	1:1.5917160000000001	2:-0.06001600000000007	3:-2.317329	4:-3.8193589999999995	5:0.907905	6:-3.124571	7:-0.07144900000000007	8:-1.061829	9:-0.6851829999999999	10:-0.2752840000000001	11:3.6963269999999997	12:3.8794690000000003	13:-1.8299360000000002	14:-1.9473989999999999	15:2.441315	16:-1.8231129999999998	17:2.657318	18:0.17293099999999995	19:-0.454046	20:-2.4547760000000003	21:-3.7171960000000004	22:1.469587	23:-0.559072	24:-2.613014	25:-1.2385190000000001	26:1.0808170000000001	27:-0.097218	28:3.9861940000000002	29:-0.8689779999999999	30:-0.372558	31:3.126285	32:1.7829549999999998	33:-1.7818260000000001	34:2.3201549999999997	35:4.450599	36:2.4950829999999997	37:2.069417	38:-3.3635780000000004	39:5.97971

10000
99993


In [ ]:
# Author : Hyunyoung2 

# To represent the format fit to SVM_Light enginea

import numpy as np


# To read vector file 
# for vector 
CBOW_testSen2Vec = ["/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/CBOW_HAMVector",
             "/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/CBOW_SPMVector"]
CBOW_trainSen2Vec = ["/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/CBOW_HAMvector",
              "/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/CBOW_SPMVector"]

SKIP_GRAM_testSen2Vec =["/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/SKIP_GRAM_HAMVector",
             "/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/SKIP_GRAM_SPMVector"]
SKIP_GRAM_trainSen2Vec = ["/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/SKIP_GRAM_HAMvector",
              "/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/SKIP_GRAM_SPMVector"]


# To store it in the 
CBOW_SVM_Lihgt_test = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/test/CBOW_SVM_Light_test"

CBOW_SVM_Lihgt_train = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/train/CBOW_SVM_Light_train"
                              
SKIP_GRAM_SVM_Lihgt_test = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/test/SKIP_GRAM_SVM_Light_test"

SKIP_GRAM_SVM_Lihgt_train = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/train/SKIP_GRAM_SVM_Light_train"
                     
# Read the file of vectors, a line is a factor in list
def readVector(file):
    
    with open(file, "r") as rf:
        lineByLine = [ tuple(x.split("\t")) for x in rf.readlines() if x != "\n" ]
        
    print(file, ":", len(lineByLine))
    
    return lineByLine


# change the form fit to SVM Light engine
def SVMLightFormat(vector, spm):
    
    for vectorIdx, vectorVal in enumerate(vector):
        temp_factor = str()
        for factorIdx, factorVal in enumerate(vectorVal):
            floatFactorVal = float(factorVal)
            if spm == True:
                if factorIdx == 0:
                    temp_factor += ("-1"+"\t"+str(factorIdx+1)+":"+str(floatFactorVal)+"\t")
                elif factorIdx == (len(vector)-1):
                    temp_factor += (str(factorIdx+1)+":"+str(floatFactorVal))
                else:
                    temp_factor += (str(factorIdx+1)+":"+str(floatFactorVal)+"\t")
            elif spm == False:
                if factorIdx == 0:
                    temp_factor += ("+1"+"\t"+str(factorIdx+1)+":"+str(floatFactorVal)+"\t")
                elif factorIdx == (len(vector)-1):
                    temp_factor += (str(factorIdx+1)+":"+str(floatFactorVal))
                else:
                    temp_factor += (str(factorIdx+1)+":"+str(floatFactorVal)+"\t")
        vector[vectorIdx] = temp_factor
    
    return vector

def writeVectorSVMLight(vector, fileHandler):
    for vectorIdx, vectorVal in enumerate(vector):
        fileHandler.write(vectorVal+"\n")
        
            
def main():
    # fixed dimensionality 
    dim = 300
    
    # CBOW 
    ## Test
    with open(CBOW_SVM_Lihgt_test, "w") as wf:
        for CBOWTestIdx, CBOWTestVal in enumerate(CBOW_testSen2Vec):
            print("reading", CBOWTestVal, "......")
            vector = readVector(CBOWTestVal)
            print("writing", CBOW_SVM_Lihgt_test, ".......\n")
            if CBOWTestIdx == 0:  # 0 means HAM(false)
                writeVectorSVMLight(SVMLightFormat(vector, False), wf)
            else:  # 1 means SPM(true)
                writeVectorSVMLight(SVMLightFormat(vector, True), wf)
    ## train
    with open(CBOW_SVM_Lihgt_train, "w") as wf:
        for CBOWTrainIdx, CBOWTrainVal in enumerate(CBOW_trainSen2Vec):
            print("reading", CBOWTrainVal, "......")
            vector = readVector(CBOWTrainVal)
            print("writing", CBOW_SVM_Lihgt_train, ".......\n")
            if CBOWTrainIdx == 0:  # 0 means HAM(false)
                writeVectorSVMLight(SVMLightFormat(vector, False), wf)
            else:  # 1 means SPM(true)
                writeVectorSVMLight(SVMLightFormat(vector, True), wf)
    # SKIP_GRAM 
    ## test
    with open(SKIP_GRAM_SVM_Lihgt_test, "w") as wf:
        for SKIP_GRAM_testIdx, SKIP_GRAM_testVal in enumerate(SKIP_GRAM_testSen2Vec):
            print("reading", SKIP_GRAM_testVal, "......")
            vector = readVector(SKIP_GRAM_testVal)
            print("writing", SKIP_GRAM_SVM_Lihgt_test, ".......\n")
            if SKIP_GRAM_testIdx == 0:  # 0 means HAM(false)
                writeVectorSVMLight(SVMLightFormat(vector, False), wf)
            else:  # 1 means SPM(true)
                writeVectorSVMLight(SVMLightFormat(vector, True), wf)
    
    ## train
    with open(SKIP_GRAM_SVM_Lihgt_train, "w") as wf:
        for SKIP_GRAM_TrainIdx, SKIP_GRAM_TrainVal in enumerate(SKIP_GRAM_trainSen2Vec):
            print("reading", SKIP_GRAM_TrainVal, "......")
            vector = readVector(SKIP_GRAM_TrainVal)
            print("writing", SKIP_GRAM_SVM_Lihgt_train, ".......\n")
            if SKIP_GRAM_TrainIdx == 0:  # 0 means HAM(false)
                writeVectorSVMLight(SVMLightFormat(vector, False), wf)
            else:  # 1 means SPM(true)
                writeVectorSVMLight(SVMLightFormat(vector, True), wf)
                
    print("changing is done!!")
    
    
main()


In [3]:
import tensorflow as tf

x = tf.constant([[37.0, -23.0], [1.0, 4.0]])
w = tf.Variable(tf.random_uniform([2, 2]))
y = tf.matmul(x, w)
output = tf.nn.softmax(y)
init_op = w.initializer

with tf.Session() as sess:
    # Run the initializer on `w`.
    sess.run(init_op)

    # Evaluate `output`. `sess.run(output)` will return a NumPy array containing
    # the result of the computation.
    print(sess.run(output))

    # Evaluate `y` and `output`. Note that `y` will only be computed once, and its
    # result used both to return `y_val` and as an input to the `tf.nn.softmax()`
    # op. Both `y_val` and `output_val` will be NumPy arrays.
    y_val, output_val = sess.run([y, output])
    print(y_val,"\n", output_val)



[[  1.94330330e-10   1.00000000e+00]
 [  6.43885076e-01   3.56114894e-01]]
[[  4.10708237  26.46854401]
 [  3.17772675   2.58545995]] 
 [[  1.94330330e-10   1.00000000e+00]
 [  6.43885076e-01   3.56114894e-01]]


In [ ]:
import tensorflow as tf

x = tf.constant([[37.0, -23.0], [1.0, 4.0]])
w = tf.constant([20])
y = tf.add(w, x)
output = tf.nn.softmax(y)

with tf.Session() as sess:
    # Run the initializer on `w`.

    # Evaluate `output`. `sess.run(output)` will return a NumPy array containing
    # the result of the computation.
    print(sess.run(output))

    # Evaluate `y` and `output`. Note that `y` will only be computed once, and its
    # result used both to return `y_val` and as an input to the `tf.nn.softmax()`
    # op. Both `y_val` and `output_val` will be NumPy arrays.
    y_val, output_val = sess.run([y, output])
    print(y_val,"\n", output_val)

In [1]:
import tensorflow as tf

x = tf.constant([[37.0, -23.0], [1.0, 4.0], [2.0, 3.0]])
w = tf.get_variable("Layer2_bias_output", [1,2], dtype=tf.float32)
y = tf.add(w, x)
output = tf.nn.softmax(y)

init_OP = tf.global_variables_initializer()

with tf.Session() as sess:
    # Run the initializer on `w`.
    sess.run(init_OP)

    # Evaluate `output`. `sess.run(output)` will return a NumPy array containing
    # the result of the computation.
    print(sess.run(output))

    # Evaluate `y` and `output`. Note that `y` will only be computed once, and its
    # result used both to return `y_val` and as an input to the `tf.nn.softmax()`
    # op. Both `y_val` and `output_val` will be NumPy arrays.
    w_val, y_val, output_val = sess.run([w, y, output])
    print(w_val)
    print
    print(y_val,"\n", output_val)

[[  1.00000000e+00   5.40436935e-27]
 [  7.46464655e-02   9.25353527e-01]
 [  3.73457432e-01   6.26542568e-01]]
[[ 0.94487703  0.46228993]]
[[ 37.94487762 -22.53771019]
 [  1.94487703   4.46228981]
 [  2.94487715   3.46228981]] 
 [[  1.00000000e+00   5.40436935e-27]
 [  7.46464655e-02   9.25353527e-01]
 [  3.73457432e-01   6.26542568e-01]]


In [1]:
import tensorflow as tf

x = tf.constant([[37.0, -23.0], [1.0, 4.0], [2.0, 3.0]])
w = tf.get_variable("Layer2_bias_output", [2,1], dtype=tf.float32)
y = tf.add(w, x)
output = tf.nn.softmax(y)

init_OP = tf.global_variables_initializer()

with tf.Session() as sess:
    # Run the initializer on `w`.
    sess.run(init_OP)

    # Evaluate `output`. `sess.run(output)` will return a NumPy array containing
    # the result of the computation.
    print(sess.run(output))

    # Evaluate `y` and `output`. Note that `y` will only be computed once, and its
    # result used both to return `y_val` and as an input to the `tf.nn.softmax()`
    # op. Both `y_val` and `output_val` will be NumPy arrays.
    w_val, y_val, output_val = sess.run([w, y, output])
    print(w_val)
    print
    print(y_val,"\n", output_val)

ValueError: Dimensions must be equal, but are 2 and 3 for 'Add' (op: 'Add') with input shapes: [2,1], [3,2].

In [ ]:
#LightNVM 

import numpy as np 

def changeFormatOfDataForSVMLight(a_list, spm) :

    for idx1, var1 in enumerate(a_list) :
        temp_str = str()
        temp = var1.split()
        for idx2, var2 in enumerate(temp) :
            temp_var = float(var2)
            if spm == True : 
                if idx2 == 0 :
                    temp_str += ("-1\t"+str(idx2+1)+":"+str(temp_var)+"\t")
                elif idx2 == (len(a_list)-1) :
                    temp_str += (str(idx2+1)+":"+str(temp_var))
                else :
                    temp_str += (str(idx2+1)+":"+str(temp_var)+"\t")
            else :
                if idx2 == 0 :
                    temp_str += ("1\t"+str(idx2+1)+":"+str(temp_var)+"\t")
                elif idx2 == (len(a_list)-1) :
                    temp_str += (str(idx2+1)+":"+str(temp_var))
                else :
                    temp_str += (str(idx2+1)+":"+str(temp_var)+"\t")
        a_list[idx1] = temp_str
    return a_list
    

def WriteArrayForSVM_light(file_handler, a_list) :
    for idx, var in enumerate(a_list) :
            if idx <= 10 :
                print (idx)
            file_handler.write(var+"\n")
            
# @ function : Read a file without blank line
# For example : 
# ["Hellow world\n", "\n", "Hi\n"] --> ["Hellow world\n", "Hi\n"]
# input : file path 
# output : a set of Lists of Words
def readAFileLineByLine (file_path) :
    f = open(file_path, "r")
    # due to iconv not dealing with conversion between EUC-KR and UTF-8
    a_whole_list = [x for x in f.readlines() if x != "\n"]
    f.close()
    # For Debugging
    print ("Currently, The file(" + file_path, ") read")    
    return a_whole_list


CBOW_testSen2Vec = ["/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/CBOW_HAMVector",
             "/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/CBOW_SPMVector"]
CBOW_trainSen2Vec = ["/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/CBOW_HAMvector",
              "/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/CBOW_SPMVector"]

SKIP_GRAM_testSen2Vec =["/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/SKIP_GRAM_HAMVector",
             "/home/hyunyoung2/My_lab/smart_conference/data/Vector/test/SKIP_GRAM_SPMVector"]
SKIP_GRAM_trainSen2Vec = ["/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/SKIP_GRAM_HAMvector",
              "/home/hyunyoung2/My_lab/smart_conference/data/Vector/train/SKIP_GRAM_SPMVector"]


# To store it in the 
CBOW_SVM_Lihgt_test = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/test/CBOW_SVM_Light_test"

CBOW_SVM_Lihgt_train = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/train/CBOW_SVM_Light_train"
                              
SKIP_GRAM_SVM_Lihgt_test = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/test/SKIP_GRAM_SVM_Light_test"

SKIP_GRAM_SVM_Lihgt_train = "/home/hyunyoung2/My_lab/smart_conference/data/SVM_Light/train/SKIP_GRAM_SVM_Light_train"
                     

def CBOWmain(test_ham, test_spm, train_ham, train_spm, target_train, target_test) :
    path1 = test_ham
    path2 = test_spm
    path3 = train_ham
    path4 = train_spm
    
    #for SVM Light 
    svm_light_train=target_train
    svm_light_test=target_test
   
    # for Test
    test_ham_list=readAFileLineByLine(path1)
    test_ham_svm = changeFormatOfDataForSVMLight(test_ham_list, False)
    
    print (len(test_ham_svm))
    
    test_spm_list=readAFileLineByLine(path2)
    test_spm_svm = changeFormatOfDataForSVMLight(test_spm_list, True)
    
    print (len(test_spm_svm))
    test_svm = test_ham_svm + test_spm_svm 
    print (test_svm[-1])
    with open(svm_light_test, "w") as svm_light_test_writer : 
            WriteArrayForSVM_light(svm_light_test_writer, test_svm)
    
    # for train
    train_ham_list=readAFileLineByLine(path3)
    train_ham_svm = changeFormatOfDataForSVMLight(train_ham_list, False)
    print (train_ham_svm[-1])
    print (len(train_ham_svm))
    
    train_spm_list=readAFileLineByLine(path4)
    train_spm_svm = changeFormatOfDataForSVMLight(train_spm_list, True)
    
    print (len(train_spm_svm))
    train_svm = train_ham_svm + train_spm_svm
    print (train_svm[-1])
    with open(svm_light_train, "w") as svm_light_train_writer : 
            WriteArrayForSVM_light(svm_light_train_writer, train_svm)
    
    print (len(test_svm))
    print (len(train_svm))
    
    
if __name__ == "__main__" :
    main(CBOW_testSen2Vec[0], CBOW_testSen2Vec[1], CBOW_trainSen2Vec[0], CBOW_trainSen2Vec[1], CBOW_SVM_Lihgt_train, CBOW_SVM_Lihgt_test)
    main(SKIP_GRAM_testSen2Vec[0], SKIP_GRAM_testSen2Vec[1], SKIP_GRAM_trainSen2Vec[0], SKIP_GRAM_trainSen2Vec[1], SKIP_GRAM_SVM_Lihgt_train, SKIP_GRAM_SVM_Lihgt_test)